#pragma once
#include <iostream>

/*
Euler problem 2:
*Each new term in the Fibonacci sequence is generated by adding the previous 
*two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

*By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
*find the sum of the even-valued terms.
*/

int Euler2()
{
	int sum = 0;
	int one = 1;
	int temp = 0;
	int const end = 4000000;
	for(int two = 2; two < end;)
	{
		if(two % 2 == 0)
		{
			sum += two;
		}
		temp = two;
		two = one + two;
		one = temp;
	}
	return sum;
}